config/routes.rb
Rails.application.routes.draw do
  resources :duenios
  resources :perros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/duenio.rb
class Duenio < ApplicationRecord
end

app/models/perro.rb
class Perro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/duenios_controller.rb
class DueniosController < ApplicationController
  before_action :set_duenio, only: [:show, :edit, :update, :destroy]

  # GET /duenios
  # GET /duenios.json
  def index
    @duenios = Duenio.all
  end

  # GET /duenios/1
  # GET /duenios/1.json
  def show
  end

  # GET /duenios/new
  def new
    @duenio = Duenio.new
  end

  # GET /duenios/1/edit
  def edit
  end

  # POST /duenios
  # POST /duenios.json
  def create
    @duenio = Duenio.new(duenio_params)

    respond_to do |format|
      if @duenio.save
        format.html { redirect_to @duenio, notice: 'Duenio was successfully created.' }
        format.json { render :show, status: :created, location: @duenio }
      else
        format.html { render :new }
        format.json { render json: @duenio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /duenios/1
  # PATCH/PUT /duenios/1.json
  def update
    respond_to do |format|
      if @duenio.update(duenio_params)
        format.html { redirect_to @duenio, notice: 'Duenio was successfully updated.' }
        format.json { render :show, status: :ok, location: @duenio }
      else
        format.html { render :edit }
        format.json { render json: @duenio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /duenios/1
  # DELETE /duenios/1.json
  def destroy
    @duenio.destroy
    respond_to do |format|
      format.html { redirect_to duenios_url, notice: 'Duenio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duenio
      @duenio = Duenio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duenio_params
      params.require(:duenio).permit(:nombre, :edad)
    end
end

app/controllers/perros_controller.rb
class PerrosController < ApplicationController
  before_action :set_perro, only: [:show, :edit, :update, :destroy]

  # GET /perros
  # GET /perros.json
  def index
    @perros = Perro.all
  end

  # GET /perros/1
  # GET /perros/1.json
  def show
  end

  # GET /perros/new
  def new
    @perro = Perro.new
  end

  # GET /perros/1/edit
  def edit
  end

  # POST /perros
  # POST /perros.json
  def create
    @perro = Perro.new(perro_params)

    respond_to do |format|
      if @perro.save
        format.html { redirect_to @perro, notice: 'Perro was successfully created.' }
        format.json { render :show, status: :created, location: @perro }
      else
        format.html { render :new }
        format.json { render json: @perro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perros/1
  # PATCH/PUT /perros/1.json
  def update
    respond_to do |format|
      if @perro.update(perro_params)
        format.html { redirect_to @perro, notice: 'Perro was successfully updated.' }
        format.json { render :show, status: :ok, location: @perro }
      else
        format.html { render :edit }
        format.json { render json: @perro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perros/1
  # DELETE /perros/1.json
  def destroy
    @perro.destroy
    respond_to do |format|
      format.html { redirect_to perros_url, notice: 'Perro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perro
      @perro = Perro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perro_params
      params.require(:perro).permit(:nombre, :edad)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/duenios_helper.rb
module DueniosHelper
end

app/helpers/perros_helper.rb
module PerrosHelper
end

app/views/duenios/_form.html.erb
<%= form_for(duenio) do |f| %>
  <% if duenio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(duenio.errors.count, "error") %> prohibited this duenio from being saved:</h2>

      <ul>
      <% duenio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :edad %>
    <%= f.number_field :edad %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/duenios/edit.html.erb
<h1>Editing Duenio</h1>

<%= render 'form', duenio: @duenio %>

<%= link_to 'Show', @duenio %> |
<%= link_to 'Back', duenios_path %>

app/views/duenios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Duenios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @duenios.each do |duenio| %>
      <tr>
        <td><%= duenio.nombre %></td>
        <td><%= duenio.edad %></td>
        <td><%= link_to 'Show', duenio %></td>
        <td><%= link_to 'Edit', edit_duenio_path(duenio) %></td>
        <td><%= link_to 'Destroy', duenio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Duenio', new_duenio_path %>

app/views/duenios/new.html.erb
<h1>New Duenio</h1>

<%= render 'form', duenio: @duenio %>

<%= link_to 'Back', duenios_path %>

app/views/duenios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @duenio.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @duenio.edad %>
</p>

<%= link_to 'Edit', edit_duenio_path(@duenio) %> |
<%= link_to 'Back', duenios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Repositorio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/perros/_form.html.erb
<%= form_for(perro) do |f| %>
  <% if perro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perro.errors.count, "error") %> prohibited this perro from being saved:</h2>

      <ul>
      <% perro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :edad %>
    <%= f.number_field :edad %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/perros/edit.html.erb
<h1>Editing Perro</h1>

<%= render 'form', perro: @perro %>

<%= link_to 'Show', @perro %> |
<%= link_to 'Back', perros_path %>

app/views/perros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Perros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perros.each do |perro| %>
      <tr>
        <td><%= perro.nombre %></td>
        <td><%= perro.edad %></td>
        <td><%= link_to 'Show', perro %></td>
        <td><%= link_to 'Edit', edit_perro_path(perro) %></td>
        <td><%= link_to 'Destroy', perro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Perro', new_perro_path %>

app/views/perros/new.html.erb
<h1>New Perro</h1>

<%= render 'form', perro: @perro %>

<%= link_to 'Back', perros_path %>

app/views/perros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @perro.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @perro.edad %>
</p>

<%= link_to 'Edit', edit_perro_path(@perro) %> |
<%= link_to 'Back', perros_path %>